Repository gituser12981u2/audio_visualizer, pull requests merged in 2024-06, with the labels that each got.

#24 Update visualizer.py - Cleaned message and terminal issue.
  audio_visualizer/visualizer.py
Labels: enhancement

#25 Implement hot-switching, threading per visualization, and better logging
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ci.yml
  .gitignore
  README.md
  ROADMAP.md
  audio_visualizer/__init__.py
  audio_visualizer/horizontal_left_to_right_visualizer.py
  audio_visualizer/horizontal_right_to_left_visualizer.py
  audio_visualizer/vertical_visualizer.py
  audio_visualizer/visualizer.py
  requirements-macos.txt
  requirements.txt
  setup.py
  tests/test_visualizations.py
Labels: bug, enhancement

#28 separated contributing and readme and complete documentation
  CONTRIBUTING.md
  README.md
  audio_visualizer/horizontal_left_to_right_visualizer.py
  audio_visualizer/horizontal_right_to_left_visualizer.py
  audio_visualizer/vertical_visualizer.py
  audio_visualizer/visualizer.py
  setup.py
Labels: documentation, good first issue

#31 V0.4.0
  CONTRIBUTING.md
  README.md
  audio_visualizer/__init__.py
  audio_visualizer/horizontal_left_to_right_visualizer.py
  audio_visualizer/horizontal_right_to_left_visualizer.py
  audio_visualizer/vertical_visualizer.py
  audio_visualizer/visualizer.py
  example_config/config.lua
  requirements.txt
  setup.py
Labels: enhancement
